### ISSUE TITLE
empty ImmutableVirtualizedList always generates a missing key prop warning

### ISSUE THREAD

**Issue by jpaas** [cooperka/react-native-immutable-list-view#30] opened 2017-10-05 13:32 UTC
version: 0.6.2

If my ImmutableVirtualizedList is empty, I will see this warning:
```
ExceptionsManager.js:73 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `VirtualizedList`. See https://fb.me/react-warning-keys for more information.
    in CellRenderer (at VirtualizedList.js:499)
    in VirtualizedList (at ImmutableVirtualizedList.js:109)
    in ImmutableVirtualizedList (at EmptyVirtualizedList.js:76)
    in EmptyVirtualizedList (at ImmutableVirtualizedList.js:102)
    in ImmutableVirtualizedList (at CpTeamList.js:19)
    in RCTView (at View.js:113)
    in View (at CpTeamList.js:18)
    in CpTeamList (at CtTeamList.js:58)
```

I've tried implementing my own `renderEmptyInList` that provides a key on the rendered component, but the warning remains.

Code:
```JSX
 render() {
    return (
      <View style={styles.container}>
        <ImmutableVirtualizedList
          immutableData={List()}
          ItemSeparatorComponent={this.renderSeparator}
          keyExtractor={(item) => item.get("id")}
          /*renderEmptyInList={this.renderEmptyInList}*/
          renderItem={this.renderItem}
        />
      </View>
    )
  }

```

**Comment by cooperka** [comment] 2017-10-10 02:24
Hmm, I'm not sure why you'd be seeing that in an empty list. I tried to reproduce this but could not. I'm going to close this issue, but please post here if you have more info! A link to a working example app would help me a lot. Cheers!

**Closed by cooperka** 2017-10-10 02:24 UTC

**Comment by jjant** [comment] 2018-01-27 04:14
@cooperka Same here

```jsx
      <ImmutableVirtualizedList immutableData={List()} />
```

**Comment by cooperka** [comment] 2018-01-29 22:25
@jjant could you post a link to a working example app to show the issue? I've tried it on my own machine and didn't see any warnings.

**Comment by Jephuff** [comment] 2018-05-08 17:11
@cooperka I found that it was because the data structure was being overwritten, but the keyExtractor wasn't. So if you had a keyExtractor like `(item) => item.get("id")` that wouldn't exist on the empty data.
I fixed it by overriding keyExtractor in the empty list so that it just returns 'empty'

https://github.com/Jephuff/react-native-immutable-list-view/commit/3c8460e009ca93940ee44050796bf24c287229b1

I can make a PR with that change if you'd like

**Comment by cooperka** [comment] 2018-05-19 22:10
Resolved by https://github.com/cooperka/react-native-immutable-list-view/pull/35.
